const ShipPoints = [
  {
    shipId: 1,
    name: "Impairor",
    points: 1,
    hullType: "Corvette",
    fitting: "",
  },
  {
    shipId: 2,
    name: "Ibis",
    points: 1,
    hullType: "Corvette",
    fitting: "",
  },
  {
    shipId: 3,
    name: "Velator",
    points: 1,
    hullType: "Corvette",
    fitting: "",
  },
  {
    shipId: 4,
    name: "Reaper",
    points: 1,
    hullType: "Corvette",
    fitting: "",
  },
  {
    shipId: 5,
    name: "Executioner",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 6,
    name: "Tormentor",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 7,
    name: "Punisher",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 8,
    name: "Magnate",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 9,
    name: "Condor",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 10,
    name: "Kestrel",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 11,
    name: "Merlin",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 12,
    name: "Heron",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 13,
    name: "Atron",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 14,
    name: "Tristan",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 15,
    name: "Incursus",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 16,
    name: "Imicus",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 17,
    name: "Slasher",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 18,
    name: "Breacher",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 19,
    name: "Rifter",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 20,
    name: "Probe",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 21,
    name: "Inquisitor",
    points: 1,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 22,
    name: "Bantam",
    points: 1,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 23,
    name: "Navitas",
    points: 1,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 24,
    name: "Burst",
    points: 1,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 25,
    name: "Crucifier",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 26,
    name: "Griffin",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 27,
    name: "Maulus",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 28,
    name: "Vigil",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 29,
    name: "Imperial Navy Slicer",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 30,
    name: "Crucifier Navy Issue",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 31,
    name: "Caldari Navy Hookbill",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 32,
    name: "Griffin Navy Issue",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 33,
    name: "Federation Navy Comet",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 34,
    name: "Maulus Navy Issue",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 35,
    name: "Republic Fleet Firetail",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 36,
    name: "Vigil Fleet Issue",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 37,
    name: "Vengeance",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 38,
    name: "Retribution",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 39,
    name: "Hawk",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 40,
    name: "Harpy",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 41,
    name: "Ishkur",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 42,
    name: "Enyo",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 43,
    name: "Wolf",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 44,
    name: "Jaguar",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 45,
    name: "Anathema",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 46,
    name: "Buzzard",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 47,
    name: "Helios",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 48,
    name: "Cheetah",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 49,
    name: "Purifier",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 50,
    name: "Manticore",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 51,
    name: "Nemesis",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 52,
    name: "Hound",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 53,
    name: "Sentinel",
    points: 5,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 54,
    name: "Kitsune",
    points: 5,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 55,
    name: "Keres",
    points: 5,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 56,
    name: "Hyena",
    points: 5,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 57,
    name: "Crusader",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 58,
    name: "Malediction",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 59,
    name: "Crow",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 60,
    name: "Raptor",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 61,
    name: "Traranis",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 62,
    name: "Ares",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 63,
    name: "Claw",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 64,
    name: "Stiletto",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 65,
    name: "Deacon",
    points: 5,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 66,
    name: "Kirin",
    points: 5,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 67,
    name: "Thalia",
    points: 5,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 68,
    name: "Scalpel",
    points: 5,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 69,
    name: "Coercer",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 70,
    name: "Dragoon",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 71,
    name: "Cormorant",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 72,
    name: "Corax",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 73,
    name: "Catalyst",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 74,
    name: "Algos",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 75,
    name: "Thrasher",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 76,
    name: "Talwar",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 77,
    name: "Pontifex",
    points: 6,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 78,
    name: "Stork",
    points: 6,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 79,
    name: "Magus",
    points: 6,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 80,
    name: "Bifrost",
    points: 6,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 81,
    name: "Heretic",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 82,
    name: "Flycatcher",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 83,
    name: "Eris",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 84,
    name: "Sabre",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 85,
    name: "Confessor",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 86,
    name: "Jackdaw",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 87,
    name: "Hecate",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 88,
    name: "Svipul",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 89,
    name: "Arbitrator",
    points: 6,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 90,
    name: "Blackbird",
    points: 6,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 91,
    name: "Celestis",
    points: 6,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 92,
    name: "Bellicose",
    points: 6,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 93,
    name: "Augoror",
    points: 9,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 94,
    name: "Osprey",
    points: 9,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 95,
    name: "Exequror",
    points: 9,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 96,
    name: "Scythe",
    points: 9,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 97,
    name: "Maller",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 98,
    name: "Omen",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 99,
    name: "Moa",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 100,
    name: "Caracal",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 101,
    name: "Vexor",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 102,
    name: "Thorax",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 103,
    name: "Stabber",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 104,
    name: "Rupture",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 105,
    name: "Augoror Navy Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 106,
    name: "Omen Navy Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 107,
    name: "Caracal Navy Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 108,
    name: "Osprey Navy Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 109,
    name: "Exequror Navy Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 110,
    name: "Vexor Navy Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 111,
    name: "Scythe Fleet Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 112,
    name: "Stabber Fleet Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 113,
    name: "Zealot",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 114,
    name: "Sacrilege",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 115,
    name: "Eagle",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 116,
    name: "Cerberus",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 117,
    name: "Ishtar",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 118,
    name: "Deimos",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 119,
    name: "Vagabond",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 120,
    name: "Munnin",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 121,
    name: "Devoter",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 122,
    name: "Onyx",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 123,
    name: "Phobos",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 124,
    name: "Broadsword",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 125,
    name: "Guardian",
    points: 16,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 126,
    name: "Basilisk",
    points: 16,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 127,
    name: "Oneiros",
    points: 16,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 128,
    name: "Scimitar",
    points: 16,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 129,
    name: "Curse",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 130,
    name: "Pilgrim",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 131,
    name: "Falcon",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 132,
    name: "Rook",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 133,
    name: "Arazu",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 134,
    name: "Lachesis",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 135,
    name: "Huginn",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 136,
    name: "Rapier",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 137,
    name: "Legion",
    points: 16.0,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 138,
    name: "Tengu",
    points: 16.0,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 139,
    name: "Proteus",
    points: 16.0,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 140,
    name: "Loki",
    points: 16.0,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 141,
    name: "Oracle",
    points: 10,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 142,
    name: "Naga",
    points: 10,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 143,
    name: "Talos",
    points: 10,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 144,
    name: "Tornado",
    points: 10,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 145,
    name: "Prophecy",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 146,
    name: "Harbinger",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 147,
    name: "Drake",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 148,
    name: "Ferox",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 149,
    name: "Brutix",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 150,
    name: "Myrmidon",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 151,
    name: "Hurricane",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 152,
    name: "Cyclone",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 153,
    name: "Harbinger Navy Issue",
    points: 15,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 154,
    name: "Drake Navy Issue",
    points: 15,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 155,
    name: "Brutix Navy Issue",
    points: 15,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 156,
    name: "Hurricane Fleet Issue",
    points: 15,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 157,
    name: "Damnation",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 158,
    name: "Absolution",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 159,
    name: "Vulture",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 160,
    name: "Nighthawk",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 161,
    name: "Astarte",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 162,
    name: "Eos",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 163,
    name: "Claymore",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 164,
    name: "Sleipnir",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 165,
    name: "Abaddon",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 166,
    name: "Apocalypse",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 167,
    name: "Armageddon",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 168,
    name: "Scorpion",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 169,
    name: "Raven",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 170,
    name: "Rokh",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 171,
    name: "Hyperion",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 172,
    name: "Megathron",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 173,
    name: "Dominix",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 174,
    name: "Tempest",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 175,
    name: "Typhoon",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 176,
    name: "Maelstrom",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 177,
    name: "Praxis",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 178,
    name: "Apocalypse Navy Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 179,
    name: "Armageddon Navy Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 180,
    name: "Scorpion Navy Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 181,
    name: "Raven Navy Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 182,
    name: "Megathron Navy Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 183,
    name: "Dominix Navy Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 184,
    name: "Tempest Fleet Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 185,
    name: "Typhoon Fleet Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 186,
    name: "Redeemer",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 187,
    name: "Widow",
    points: 25,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 188,
    name: "Sin",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 189,
    name: "Panther",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 190,
    name: "Paladin",
    points: 24,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 191,
    name: "Golem",
    points: 24,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 192,
    name: "Kronos",
    points: 24,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 193,
    name: "Vargur",
    points: 24,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 194,
    name: "Bestower",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 195,
    name: "Sigil",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 196,
    name: "Badger",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 197,
    name: "Tayra",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 198,
    name: "Nereus",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 199,
    name: "Kryos",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 200,
    name: "Epithal",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 201,
    name: "Miasmos",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 202,
    name: "Iteron Mark V",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 203,
    name: "Hoarder",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 204,
    name: "Mammoth",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 205,
    name: "Wreathe",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 206,
    name: "Dramiel",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 207,
    name: "Cruor",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 208,
    name: "Worm",
    points: 5,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 209,
    name: "Garmur",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 210,
    name: "Succubus",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 211,
    name: "Astero",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 212,
    name: "Daredevil",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 213,
    name: "Cynabal",
    points: 9,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 214,
    name: "Ashimmu",
    points: 9,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 215,
    name: "Gila",
    points: 11,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 216,
    name: "Orthrus",
    points: 8,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 217,
    name: "Phantasm",
    points: 9,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 218,
    name: "Stratios",
    points: 9,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 219,
    name: "Vigilant",
    points: 9,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 220,
    name: "Machariel",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 221,
    name: "Bhaalgorn",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 222,
    name: "Rattlesnake",
    points: 25,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 223,
    name: "Barghest",
    points: 20,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 224,
    name: "Nightmare",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 225,
    name: "Vindicator",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 226,
    name: "Gnosis",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 227,
    name: "Sunesis",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 228,
    name: "Thunderchild",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 229,
    name: "Stormbringer",
    points: 6,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 230,
    name: "Skybreaker",
    points: 1,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 231,
    name: "Leshak",
    points: 25,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 232,
    name: "Zarmazd",
    points: 18,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 233,
    name: "Drekevak",
    points: 17,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 234,
    name: "Ikitursa",
    points: 17,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 235,
    name: "Rodiva",
    points: 11,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 236,
    name: "Draugur",
    points: 11,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 237,
    name: "Vedmak",
    points: 10,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 238,
    name: "Kikimora",
    points: 8,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 239,
    name: "Nergal",
    points: 7,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 240,
    name: "Damavik",
    points: 5,
    hullType: "Frigate",
    fitting: "",
  },
];
export default ShipPoints;
