const ShipPoints = [
  {
    shipId: 1,
    shipName: "Impairor",
    points: 1,
    hullType: "Corvette",
    fitting: "",
  },
  {
    shipId: 2,
    shipName: "Ibis",
    points: 1,
    hullType: "Corvette",
    fitting: "",
  },
  {
    shipId: 3,
    shipName: "Velator",
    points: 1,
    hullType: "Corvette",
    fitting: "",
  },
  {
    shipId: 4,
    shipName: "Reaper",
    points: 1,
    hullType: "Corvette",
    fitting: "",
  },
  {
    shipId: 5,
    shipName: "Executioner",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 6,
    shipName: "Tormentor",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 7,
    shipName: "Punisher",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 8,
    shipName: "Magnate",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 9,
    shipName: "Condor",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 10,
    shipName: "Kestrel",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 11,
    shipName: "Merlin",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 12,
    shipName: "Heron",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 13,
    shipName: "Atron",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 14,
    shipName: "Tristan",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 15,
    shipName: "Incursus",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 16,
    shipName: "Imicus",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 17,
    shipName: "Slasher",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 18,
    shipName: "Breacher",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 19,
    shipName: "Rifter",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 20,
    shipName: "Probe",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 21,
    shipName: "Inquisitor",
    points: 1,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 22,
    shipName: "Bantam",
    points: 1,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 23,
    shipName: "Navitas",
    points: 1,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 24,
    shipName: "Burst",
    points: 1,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 25,
    shipName: "Crucifier",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 26,
    shipName: "Griffin",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 27,
    shipName: "Maulus",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 28,
    shipName: "Vigil",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 29,
    shipName: "Imperial Navy Slicer",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 30,
    shipName: "Crucifier Navy Issue",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 31,
    shipName: "Caldari Navy Hookbill",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 32,
    shipName: "Griffin Navy Issue",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 33,
    shipName: "Federation Navy Comet",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 34,
    shipName: "Maulus Navy Issue",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 35,
    shipName: "Republic Fleet Firetail",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 36,
    shipName: "Vigil Fleet Issue",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 37,
    shipName: "Vengeance",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 38,
    shipName: "Retribution",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 39,
    shipName: "Hawk",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 40,
    shipName: "Harpy",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 41,
    shipName: "Ishkur",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 42,
    shipName: "Enyo",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 43,
    shipName: "Wolf",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 44,
    shipName: "Jaguar",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 45,
    shipName: "Anathema",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 46,
    shipName: "Buzzard",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 47,
    shipName: "Helios",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 48,
    shipName: "Cheetah",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 49,
    shipName: "Purifier",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 50,
    shipName: "Manticore",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 51,
    shipName: "Nemesis",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 52,
    shipName: "Hound",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 53,
    shipName: "Sentinel",
    points: 5,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 54,
    shipName: "Kitsune",
    points: 5,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 55,
    shipName: "Keres",
    points: 5,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 56,
    shipName: "Hyena",
    points: 5,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 57,
    shipName: "Crusader",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 58,
    shipName: "Malediction",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 59,
    shipName: "Crow",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 60,
    shipName: "Raptor",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 61,
    shipName: "Traranis",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 62,
    shipName: "Ares",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 63,
    shipName: "Claw",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 64,
    shipName: "Stiletto",
    points: 3,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 65,
    shipName: "Deacon",
    points: 5,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 66,
    shipName: "Kirin",
    points: 5,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 67,
    shipName: "Thalia",
    points: 5,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 68,
    shipName: "Scalpel",
    points: 5,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 69,
    shipName: "Coercer",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 70,
    shipName: "Dragoon",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 71,
    shipName: "Cormorant",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 72,
    shipName: "Corax",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 73,
    shipName: "Catalyst",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 74,
    shipName: "Algos",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 75,
    shipName: "Thrasher",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 76,
    shipName: "Talwar",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 77,
    shipName: "Pontifex",
    points: 6,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 78,
    shipName: "Stork",
    points: 6,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 79,
    shipName: "Magus",
    points: 6,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 80,
    shipName: "Bifrost",
    points: 6,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 81,
    shipName: "Heretic",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 82,
    shipName: "Flycatcher",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 83,
    shipName: "Eris",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 84,
    shipName: "Sabre",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 85,
    shipName: "Confessor",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 86,
    shipName: "Jackdaw",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 87,
    shipName: "Hecate",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 88,
    shipName: "Svipul",
    points: 4,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 89,
    shipName: "Arbitrator",
    points: 6,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 90,
    shipName: "Blackbird",
    points: 6,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 91,
    shipName: "Celestis",
    points: 6,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 92,
    shipName: "Bellicose",
    points: 6,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 93,
    shipName: "Augoror",
    points: 9,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 94,
    shipName: "Osprey",
    points: 9,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 95,
    shipName: "Exequror",
    points: 9,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 96,
    shipName: "Scythe",
    points: 9,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 97,
    shipName: "Maller",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 98,
    shipName: "Omen",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 99,
    shipName: "Moa",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 100,
    shipName: "Caracal",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 101,
    shipName: "Vexor",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 102,
    shipName: "Thorax",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 103,
    shipName: "Stabber",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 104,
    shipName: "Rupture",
    points: 4,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 105,
    shipName: "Augoror Navy Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 106,
    shipName: "Omen Navy Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 107,
    shipName: "Caracal Navy Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 108,
    shipName: "Osprey Navy Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 109,
    shipName: "Exequror Navy Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 110,
    shipName: "Vexor Navy Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 111,
    shipName: "Scythe Fleet Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 112,
    shipName: "Stabber Fleet Issue",
    points: 7,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 113,
    shipName: "Zealot",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 114,
    shipName: "Sacrilege",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 115,
    shipName: "Eagle",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 116,
    shipName: "Cerberus",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 117,
    shipName: "Ishtar",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 118,
    shipName: "Deimos",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 119,
    shipName: "Vagabond",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 120,
    shipName: "Munnin",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 121,
    shipName: "Devoter",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 122,
    shipName: "Onyx",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 123,
    shipName: "Phobos",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 124,
    shipName: "Broadsword",
    points: 12,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 125,
    shipName: "Guardian",
    points: 16,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 126,
    shipName: "Basilisk",
    points: 16,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 127,
    shipName: "Oneiros",
    points: 16,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 128,
    shipName: "Scimitar",
    points: 16,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 129,
    shipName: "Curse",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 130,
    shipName: "Pilgrim",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 131,
    shipName: "Falcon",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 132,
    shipName: "Rook",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 133,
    shipName: "Arazu",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 134,
    shipName: "Lachesis",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 135,
    shipName: "Huginn",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 136,
    shipName: "Rapier",
    points: 13,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 137,
    shipName: "Legion",
    points: 16.0,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 138,
    shipName: "Tengu",
    points: 16.0,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 139,
    shipName: "Proteus",
    points: 16.0,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 140,
    shipName: "Loki",
    points: 16.0,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 141,
    shipName: "Oracle",
    points: 10,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 142,
    shipName: "Naga",
    points: 10,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 143,
    shipName: "Talos",
    points: 10,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 144,
    shipName: "Tornado",
    points: 10,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 145,
    shipName: "Prophecy",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 146,
    shipName: "Harbinger",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 147,
    shipName: "Drake",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 148,
    shipName: "Ferox",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 149,
    shipName: "Brutix",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 150,
    shipName: "Myrmidon",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 151,
    shipName: "Hurricane",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 152,
    shipName: "Cyclone",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 153,
    shipName: "Harbinger Navy Issue",
    points: 15,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 154,
    shipName: "Drake Navy Issue",
    points: 15,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 155,
    shipName: "Brutix Navy Issue",
    points: 15,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 156,
    shipName: "Hurricane Fleet Issue",
    points: 15,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 157,
    shipName: "Damnation",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 158,
    shipName: "Absolution",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 159,
    shipName: "Vulture",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 160,
    shipName: "Nighthawk",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 161,
    shipName: "Astarte",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 162,
    shipName: "Eos",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 163,
    shipName: "Claymore",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 164,
    shipName: "Sleipnir",
    points: 18,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 165,
    shipName: "Abaddon",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 166,
    shipName: "Apocalypse",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 167,
    shipName: "Armageddon",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 168,
    shipName: "Scorpion",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 169,
    shipName: "Raven",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 170,
    shipName: "Rokh",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 171,
    shipName: "Hyperion",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 172,
    shipName: "Megathron",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 173,
    shipName: "Dominix",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 174,
    shipName: "Tempest",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 175,
    shipName: "Typhoon",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 176,
    shipName: "Maelstrom",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 177,
    shipName: "Praxis",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 178,
    shipName: "Apocalypse Navy Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 179,
    shipName: "Armageddon Navy Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 180,
    shipName: "Scorpion Navy Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 181,
    shipName: "Raven Navy Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 182,
    shipName: "Megathron Navy Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 183,
    shipName: "Dominix Navy Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 184,
    shipName: "Tempest Fleet Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 185,
    shipName: "Typhoon Fleet Issue",
    points: 21,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 186,
    shipName: "Redeemer",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 187,
    shipName: "Widow",
    points: 25,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 188,
    shipName: "Sin",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 189,
    shipName: "Panther",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 190,
    shipName: "Paladin",
    points: 24,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 191,
    shipName: "Golem",
    points: 24,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 192,
    shipName: "Kronos",
    points: 24,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 193,
    shipName: "Vargur",
    points: 24,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 194,
    shipName: "Bestower",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 195,
    shipName: "Sigil",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 196,
    shipName: "Badger",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 197,
    shipName: "Tayra",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 198,
    shipName: "Nereus",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 199,
    shipName: "Kryos",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 200,
    shipName: "Epithal",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 201,
    shipName: "Miasmos",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 202,
    shipName: "Iteron Mark V",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 203,
    shipName: "Hoarder",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 204,
    shipName: "Mammoth",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 205,
    shipName: "Wreathe",
    points: 2,
    hullType: "Industrial",
    fitting: "",
  },
  {
    shipId: 206,
    shipName: "Dramiel",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 207,
    shipName: "Cruor",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 208,
    shipName: "Worm",
    points: 5,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 209,
    shipName: "Garmur",
    points: 2,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 210,
    shipName: "Succubus",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 211,
    shipName: "Astero",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 212,
    shipName: "Daredevil",
    points: 4,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 213,
    shipName: "Cynabal",
    points: 9,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 214,
    shipName: "Ashimmu",
    points: 9,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 215,
    shipName: "Gila",
    points: 11,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 216,
    shipName: "Orthrus",
    points: 8,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 217,
    shipName: "Phantasm",
    points: 9,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 218,
    shipName: "Stratios",
    points: 9,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 219,
    shipName: "Vigilant",
    points: 9,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 220,
    shipName: "Machariel",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 221,
    shipName: "Bhaalgorn",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 222,
    shipName: "Rattlesnake",
    points: 25,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 223,
    shipName: "Barghest",
    points: 20,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 224,
    shipName: "Nightmare",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 225,
    shipName: "Vindicator",
    points: 23,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 226,
    shipName: "Gnosis",
    points: 13,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 227,
    shipName: "Sunesis",
    points: 3,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 228,
    shipName: "Thunderchild",
    points: 19,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 229,
    shipName: "Stormbringer",
    points: 6,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 230,
    shipName: "Skybreaker",
    points: 1,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 231,
    shipName: "Leshak",
    points: 25,
    hullType: "Battleship",
    fitting: "",
  },
  {
    shipId: 232,
    shipName: "Zarmazd",
    points: 18,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 233,
    shipName: "Drekevak",
    points: 17,
    hullType: "Battlecruiser",
    fitting: "",
  },
  {
    shipId: 234,
    shipName: "Ikitursa",
    points: 17,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 235,
    shipName: "Rodiva",
    points: 11,
    hullType: "Logistics",
    fitting: "",
  },
  {
    shipId: 236,
    shipName: "Draugur",
    points: 11,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 237,
    shipName: "Vedmak",
    points: 10,
    hullType: "Cruiser",
    fitting: "",
  },
  {
    shipId: 238,
    shipName: "Kikimora",
    points: 8,
    hullType: "Destroyer",
    fitting: "",
  },
  {
    shipId: 239,
    shipName: "Nergal",
    points: 7,
    hullType: "Frigate",
    fitting: "",
  },
  {
    shipId: 240,
    shipName: "Damavik",
    points: 5,
    hullType: "Frigate",
    fitting: "",
  },
];
export default ShipPoints;
